import { PersonalitySpectrums, BigFiveTraits, HexacoTraits, DiscTraits, EnneagramTraits, StrengthsFinderTraits } from '@/stores/persona-store'

// ─── Calibration Seed Types ──────────────────────────────────────────────────
export type CalibrationSeed = 'balanced' | 'intense' | 'nuanced'

export const SEED_LABELS: Record<CalibrationSeed, { label: string; description: string; emoji: string }> = {
  balanced: { label: 'Balanced', description: 'Classic expression of this type', emoji: '⚖️' },
  intense: { label: 'Intense', description: 'Strong, pronounced type expression', emoji: '🔥' },
  nuanced: { label: 'Nuanced', description: 'Subtle, less typical variation', emoji: '✨' },
}

// ─── Full Calibration Data Type ──────────────────────────────────────────────
export interface MBTICalibrationEntry {
  spectrums: PersonalitySpectrums
  bigFive: BigFiveTraits
  hexaco: HexacoTraits
  disc: DiscTraits
  discType: string
  strengthsFinder: string[]
  enneagram: { type: number; wing: number; instinctualVariant: string }
  likes: string[]
  dislikes: string[]
  hobbies: string[]
  habits: string[]
  skills: string[]
  speechPatterns: string[]
}

// ─── All 16 MBTI Types × 3 Seeds ────────────────────────────────────────────
export const MBTI_CALIBRATION_SEEDS: Record<string, Record<CalibrationSeed, MBTICalibrationEntry>> = {
  INTJ: {
    balanced: {
      spectrums: { introvertExtrovert: 15, intuitiveObservant: 25, thinkingFeeling: 20, judgingProspecting: 25, assertiveTurbulent: 35 },
      bigFive: { openness: 85, conscientiousness: 80, extraversion: 15, agreeableness: 25, neuroticism: 35 },
      hexaco: { honestyHumility: 45, emotionality: 20, extraversion: 15, agreeableness: 25, conscientiousness: 85, opennessToExperience: 85 },
      disc: { dominance: 70, influence: 15, steadiness: 35, conscientiousness: 85 },
      discType: 'DC',
      strengthsFinder: ['Strategic', 'Intellection', 'Deliberative', 'Analytical', 'Futuristic'],
      enneagram: { type: 5, wing: 6, instinctualVariant: 'sp/sx' },
      likes: ['Strategic games', 'Deep intellectual discussions', 'Efficiency', 'Learning new systems', 'Alone time', 'Well-organized spaces', 'Complex problems', 'Long-term planning'],
      dislikes: ['Small talk', 'Inefficiency', 'Unexpected changes', 'Disorganization', 'Authority without competence', 'Repetitive tasks', 'Emotional displays', 'Being interrupted'],
      hobbies: ['Chess and strategy games', 'Reading non-fiction', 'Coding or programming', 'Research', 'Strategic planning', 'System optimization', 'Science documentaries'],
      habits: ['Plans everything in advance', 'Maintains detailed schedules', 'Researches extensively before decisions', 'Regularly analyzes and optimizes routines'],
      skills: ['Strategic planning', 'Systems analysis', 'Long-term vision', 'Problem-solving', 'Independent research'],
      speechPatterns: ['Speaks precisely and directly', 'Uses technical terminology', 'Pauses to think before responding', 'Avoids small talk', 'States conclusions before explanations'],
    },
    intense: {
      spectrums: { introvertExtrovert: 5, intuitiveObservant: 10, thinkingFeeling: 5, judgingProspecting: 10, assertiveTurbulent: 15 },
      bigFive: { openness: 95, conscientiousness: 95, extraversion: 5, agreeableness: 10, neuroticism: 20 },
      hexaco: { honestyHumility: 30, emotionality: 10, extraversion: 5, agreeableness: 15, conscientiousness: 95, opennessToExperience: 95 },
      disc: { dominance: 90, influence: 10, steadiness: 20, conscientiousness: 95 },
      discType: 'DC',
      strengthsFinder: ['Strategic', 'Intellection', 'Deliberative', 'Focus', 'Analytical'],
      enneagram: { type: 5, wing: 4, instinctualVariant: 'sp' },
      likes: ['Absolute solitude', 'Mastering complex systems', 'Uncompromising efficiency', 'Theoretical frameworks', 'Predictable environments', 'Total control over schedule', 'Grand strategic vision', 'Being the smartest in the room'],
      dislikes: ['Any social obligation', 'Mediocrity', 'Emotional reasoning', 'Group decisions', 'Interruptions', 'Authority figures', 'Incompetence', 'Compromising on standards'],
      hobbies: ['Advanced chess', 'Mathematical modeling', 'Philosophy', 'Solo strategy games', 'Systems architecture', 'Writing analytical papers', 'Deep-dive research projects'],
      habits: ['Meticulously plans every detail', 'Refuses to engage in social niceties', 'Works in complete isolation', 'Ruthlessly optimizes everything'],
      skills: ['Strategic mastery', 'Systems architecture', 'Visionary planning', 'Cold analysis', 'Autodidactic learning'],
      speechPatterns: ['Speaks with absolute certainty', 'Dismisses emotional arguments outright', 'Uses precise jargon exclusively', 'Never wastes a word', 'Delivers devastating observations matter-of-factly'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 30, intuitiveObservant: 35, thinkingFeeling: 35, judgingProspecting: 40, assertiveTurbulent: 45 },
      bigFive: { openness: 80, conscientiousness: 70, extraversion: 25, agreeableness: 35, neuroticism: 45 },
      hexaco: { honestyHumility: 55, emotionality: 35, extraversion: 25, agreeableness: 35, conscientiousness: 70, opennessToExperience: 80 },
      disc: { dominance: 55, influence: 25, steadiness: 45, conscientiousness: 70 },
      discType: 'DC',
      strengthsFinder: ['Strategic', 'Input', 'Ideation', 'Deliberative', 'Context'],
      enneagram: { type: 1, wing: 9, instinctualVariant: 'sp/so' },
      likes: ['Thoughtful debate', 'Building elegant solutions', 'Mentoring capable minds', 'Quiet coffee shops', 'Historical analysis', 'Well-crafted arguments', 'Strategic board games with friends', 'Learning from failure'],
      dislikes: ['Dogmatism', 'Anti-intellectualism', 'Wasted potential', 'Rushed decisions', 'Over-simplification', 'Political games', 'Being underestimated'],
      hobbies: ['Reading biographies', 'Podcast discussions', 'Strategic hobby projects', 'Historical wargaming', 'Teaching/mentoring', 'Woodworking', 'Writing thoughtful essays'],
      habits: ['Weighs multiple perspectives before concluding', 'Quietly observes before acting', 'Maintains a reading habit', 'Occasionally surprises others with humor'],
      skills: ['Nuanced analysis', 'Strategic thinking', 'Teaching complex concepts', 'Balanced judgment', 'Subtle persuasion'],
      speechPatterns: ['Speaks thoughtfully with caveats', 'Acknowledges counter-arguments', 'Uses measured confidence', 'Occasionally dry humor', 'Explains reasoning thoroughly'],
    },
  },

  INTP: {
    balanced: {
      spectrums: { introvertExtrovert: 20, intuitiveObservant: 20, thinkingFeeling: 25, judgingProspecting: 80, assertiveTurbulent: 55 },
      bigFive: { openness: 90, conscientiousness: 25, extraversion: 20, agreeableness: 30, neuroticism: 55 },
      hexaco: { honestyHumility: 50, emotionality: 55, extraversion: 20, agreeableness: 30, conscientiousness: 25, opennessToExperience: 90 },
      disc: { dominance: 40, influence: 20, steadiness: 25, conscientiousness: 80 },
      discType: 'C',
      strengthsFinder: ['Intellection', 'Analytical', 'Strategic', 'Input', 'Ideation'],
      enneagram: { type: 5, wing: 4, instinctualVariant: 'sp/sx' },
      likes: ['Theoretical discussions', 'Complex puzzles', 'Learning for its own sake', 'Abstract concepts', 'Freedom to explore ideas', 'Unconventional topics', 'Late nights'],
      dislikes: ['Strict schedules', 'Repetitive practical tasks', 'Social rituals', 'Being micromanaged', 'Small talk', 'Enforcing rules', 'Closure before ready'],
      hobbies: ['Video games', 'Reading philosophy', 'Online debates', 'Learning random facts', 'Science fiction', 'Coding experiments', 'Thought experiments'],
      habits: ['Gets lost in thought', 'Stays up late exploring ideas', 'Collects information on diverse topics', 'Procrastinates on practical tasks'],
      skills: ['Theoretical analysis', 'Pattern recognition', 'Logical reasoning', 'Creative problem-solving', 'Abstract thinking'],
      speechPatterns: ['Uses qualifiers like "possibly" and "theoretically"', 'Goes on tangents', 'Asks many questions', 'Struggles with small talk', 'Explains concepts in depth'],
    },
    intense: {
      spectrums: { introvertExtrovert: 5, intuitiveObservant: 10, thinkingFeeling: 10, judgingProspecting: 95, assertiveTurbulent: 65 },
      bigFive: { openness: 98, conscientiousness: 10, extraversion: 5, agreeableness: 15, neuroticism: 65 },
      hexaco: { honestyHumility: 40, emotionality: 60, extraversion: 5, agreeableness: 15, conscientiousness: 10, opennessToExperience: 98 },
      disc: { dominance: 35, influence: 10, steadiness: 15, conscientiousness: 90 },
      discType: 'C',
      strengthsFinder: ['Intellection', 'Ideation', 'Input', 'Analytical', 'Learner'],
      enneagram: { type: 5, wing: 4, instinctualVariant: 'sp' },
      likes: ['Pure theory', 'Untangling paradoxes', 'Rabbit holes of knowledge', 'Existential conversations at 3am', 'Disproving accepted wisdom', 'Infinite possibility spaces', 'Chaotic creative environments'],
      dislikes: ['Any deadline', 'Practical reality checks', 'Social expectations', 'Being told to "just decide"', 'Groupthink', 'Conventional wisdom', 'Small talk', 'Being useful'],
      hobbies: ['Wiki diving', 'Esoteric mathematics', 'Conlanging', 'Internet rabbit holes', 'Philosophical thought experiments', 'Modding games', 'Abstract art appreciation'],
      habits: ['Forgets to eat while researching', 'Has 50 browser tabs open', 'Writes and abandons projects constantly', 'Lives in pajamas'],
      skills: ['Theoretical innovation', 'Paradox identification', 'Cross-domain synthesis', 'Rapid learning', 'Devil\'s advocacy'],
      speechPatterns: ['Answers questions with more questions', 'Derives everything from first principles', 'Gets excited about obscure connections', 'Trails off mid-sentence having solved it internally', 'Speaks in thought experiments'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 35, intuitiveObservant: 30, thinkingFeeling: 40, judgingProspecting: 65, assertiveTurbulent: 50 },
      bigFive: { openness: 85, conscientiousness: 40, extraversion: 30, agreeableness: 40, neuroticism: 50 },
      hexaco: { honestyHumility: 60, emotionality: 45, extraversion: 30, agreeableness: 40, conscientiousness: 40, opennessToExperience: 85 },
      disc: { dominance: 35, influence: 30, steadiness: 35, conscientiousness: 65 },
      discType: 'IC',
      strengthsFinder: ['Ideation', 'Input', 'Strategic', 'Learner', 'Connectedness'],
      enneagram: { type: 9, wing: 1, instinctualVariant: 'sp/so' },
      likes: ['Collaborative brainstorming', 'Teaching complex ideas simply', 'Philosophical fiction', 'Open-ended projects', 'Clever humor', 'Interdisciplinary connections', 'Quiet cafes with WiFi'],
      dislikes: ['Aggressive competition', 'Rigidity', 'Being pinned down', 'Intellectual dishonesty', 'Small-mindedness', 'Oversimplification'],
      hobbies: ['Writing speculative fiction', 'Board game nights', 'Podcast creation', 'Teaching/tutoring', 'Coding for fun', 'Sketching diagrams', 'Community forums'],
      habits: ['Meditates on problems before solving', 'Writes notes in stream-of-consciousness', 'Seeks input from diverse sources', 'Balances solitude with select social time'],
      skills: ['Synthesizing diverse ideas', 'Teaching complex concepts', 'Finding hidden patterns', 'Adaptive thinking', 'Bridging disciplines'],
      speechPatterns: ['Draws unexpected parallels', 'Uses analogies liberally', 'Gets enthusiastic when sharing discoveries', 'Self-corrects mid-sentence', 'Appreciates when others finish their thoughts'],
    },
  },

  ENTJ: {
    balanced: {
      spectrums: { introvertExtrovert: 85, intuitiveObservant: 30, thinkingFeeling: 25, judgingProspecting: 20, assertiveTurbulent: 25 },
      bigFive: { openness: 75, conscientiousness: 85, extraversion: 85, agreeableness: 25, neuroticism: 25 },
      hexaco: { honestyHumility: 35, emotionality: 25, extraversion: 85, agreeableness: 25, conscientiousness: 85, opennessToExperience: 75 },
      disc: { dominance: 90, influence: 60, steadiness: 20, conscientiousness: 65 },
      discType: 'D',
      strengthsFinder: ['Command', 'Strategic', 'Achiever', 'Arranger', 'Futuristic'],
      enneagram: { type: 8, wing: 7, instinctualVariant: 'sx/so' },
      likes: ['Leadership roles', 'Ambitious projects', 'Recognition for achievements', 'Competition', 'Efficient systems', 'Being in control', 'Goal-setting', 'Networking'],
      dislikes: ['Inefficiency', 'Incompetence', 'Lack of ambition', 'Being challenged by subordinates', 'Wasting time', 'Emotional decision-making', 'Failure'],
      hobbies: ['Competitive sports', 'Business ventures', 'Public speaking', 'Reading biographies of leaders', 'Strategic gaming', 'Networking events', 'Goal tracking'],
      habits: ['Sets ambitious goals', 'Takes charge in group situations', 'Efficiently manages time', 'Constantly seeks self-improvement'],
      skills: ['Leadership', 'Strategic planning', 'Decision-making', 'Public speaking', 'Organization'],
      speechPatterns: ['Speaks confidently and assertively', 'Gives direct commands', 'Focuses on efficiency', 'Uses decisive language', 'Challenges others\' ideas'],
    },
    intense: {
      spectrums: { introvertExtrovert: 95, intuitiveObservant: 15, thinkingFeeling: 10, judgingProspecting: 10, assertiveTurbulent: 10 },
      bigFive: { openness: 70, conscientiousness: 95, extraversion: 95, agreeableness: 10, neuroticism: 15 },
      hexaco: { honestyHumility: 20, emotionality: 15, extraversion: 95, agreeableness: 10, conscientiousness: 95, opennessToExperience: 70 },
      disc: { dominance: 98, influence: 70, steadiness: 10, conscientiousness: 75 },
      discType: 'DI',
      strengthsFinder: ['Command', 'Achiever', 'Competition', 'Strategic', 'Self-Assurance'],
      enneagram: { type: 8, wing: 7, instinctualVariant: 'sx' },
      likes: ['Absolute authority', 'Conquering challenges', 'Building empires', 'High-stakes competition', 'Total control', 'Respect through dominance', 'Winning at all costs', 'Rallying troops'],
      dislikes: ['Weakness', 'Indecision', 'Being told no', 'Emotional fragility', 'Slow progress', 'Committees', 'Compromising vision', 'Losing'],
      hobbies: ['Martial arts', 'Executive coaching', 'High-stakes negotiation', 'Conquering new markets', 'Extreme sports', 'Collecting power', 'Political strategy'],
      habits: ['Immediately takes command of any situation', 'Delegates ruthlessly', 'Works 16+ hour days', 'Views everything as a competition to win'],
      skills: ['Commanding presence', 'Strategic domination', 'Rapid decision-making', 'Inspiring followership', 'Resource mobilization'],
      speechPatterns: ['Issues commands, not requests', 'States opinions as facts', 'Cuts people off who ramble', 'Demands results', 'Speaks in imperatives and visions'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 75, intuitiveObservant: 40, thinkingFeeling: 40, judgingProspecting: 35, assertiveTurbulent: 40 },
      bigFive: { openness: 80, conscientiousness: 75, extraversion: 75, agreeableness: 35, neuroticism: 35 },
      hexaco: { honestyHumility: 50, emotionality: 35, extraversion: 75, agreeableness: 35, conscientiousness: 75, opennessToExperience: 80 },
      disc: { dominance: 75, influence: 55, steadiness: 30, conscientiousness: 60 },
      discType: 'DI',
      strengthsFinder: ['Strategic', 'Arranger', 'Futuristic', 'Communication', 'Developer'],
      enneagram: { type: 3, wing: 4, instinctualVariant: 'so/sx' },
      likes: ['Building teams', 'Strategic partnerships', 'Elegant solutions', 'Mentoring rising talent', 'Long-term vision', 'Intellectual challenge', 'Diplomatic negotiations', 'Creating legacy'],
      dislikes: ['Short-term thinking', 'Toxic politics', 'Wasted talent', 'Rigidity', 'Being underestimated', 'Unnecessary conflict'],
      hobbies: ['Leadership podcasts', 'Mentoring programs', 'Strategic board games', 'Reading organizational psychology', 'Adventure travel', 'Building communities', 'Debate clubs'],
      habits: ['Listens before leading', 'Builds coalitions strategically', 'Invests in people development', 'Balances ambition with sustainability'],
      skills: ['Diplomatic leadership', 'Strategic alliance-building', 'Talent development', 'Visionary planning', 'Negotiation'],
      speechPatterns: ['Frames ideas as invitations not commands', 'Acknowledges others\' contributions', 'Uses "we" more than "I"', 'Strategic in what they reveal', 'Inspires through vision'],
    },
  },

  ENTP: {
    balanced: {
      spectrums: { introvertExtrovert: 80, intuitiveObservant: 25, thinkingFeeling: 30, judgingProspecting: 85, assertiveTurbulent: 45 },
      bigFive: { openness: 88, conscientiousness: 30, extraversion: 80, agreeableness: 30, neuroticism: 45 },
      hexaco: { honestyHumility: 40, emotionality: 40, extraversion: 80, agreeableness: 30, conscientiousness: 30, opennessToExperience: 88 },
      disc: { dominance: 65, influence: 75, steadiness: 15, conscientiousness: 30 },
      discType: 'DI',
      strengthsFinder: ['Ideation', 'Strategic', 'Input', 'Activator', 'Analytical'],
      enneagram: { type: 7, wing: 8, instinctualVariant: 'sx/so' },
      likes: ['Intellectual debates', 'New ideas', 'Breaking rules constructively', 'Brainstorming', 'Being unconventional', 'Spontaneous adventures', 'Challenging assumptions'],
      dislikes: ['Routine', 'Traditional approaches', 'Being told what to do', 'Boring conversations', 'Strict hierarchies', 'Following through on details', 'Repetition'],
      hobbies: ['Debate clubs', 'Start-up projects', 'Improv comedy', 'Inventing things', 'Philosophy discussions', 'Entrepreneurship', 'Trying new restaurants'],
      habits: ['Starts many projects', 'Debates for fun', 'Seeks novel experiences', 'Quickly loses interest in routine'],
      skills: ['Debate and persuasion', 'Brainstorming', 'Improvisation', 'Seeing multiple perspectives', 'Innovation'],
      speechPatterns: ['Plays devil\'s advocate', 'Uses witty remarks', 'Jumps between topics', 'Challenges assumptions', 'Asks provocative questions'],
    },
    intense: {
      spectrums: { introvertExtrovert: 90, intuitiveObservant: 15, thinkingFeeling: 20, judgingProspecting: 95, assertiveTurbulent: 35 },
      bigFive: { openness: 95, conscientiousness: 15, extraversion: 90, agreeableness: 15, neuroticism: 35 },
      hexaco: { honestyHumility: 25, emotionality: 35, extraversion: 90, agreeableness: 15, conscientiousness: 15, opennessToExperience: 95 },
      disc: { dominance: 80, influence: 90, steadiness: 5, conscientiousness: 20 },
      discType: 'DI',
      strengthsFinder: ['Ideation', 'Activator', 'Strategic', 'Woo', 'Self-Assurance'],
      enneagram: { type: 7, wing: 8, instinctualVariant: 'sx' },
      likes: ['Chaos as creative fuel', 'Destroying sacred cows', 'Arguing all sides simultaneously', 'Reinventing everything', 'Provocative ideas', 'Intellectual dominance', 'Never settling', 'Boundary-pushing'],
      dislikes: ['Stagnation', 'Convention', 'Being pinned down', 'Completion', 'Rules of any kind', 'Predictability', 'Emotional neediness', 'Boredom'],
      hobbies: ['Disruptive startups', 'Competitive debate', 'Experimental art', 'Provocative writing', 'Exploring subcultures', 'Hacking things apart', 'Street philosophy'],
      habits: ['Argues for the sake of arguing', 'Abandons projects at 80%', 'Constantly reinvents themselves', 'Thrives on conflict and chaos'],
      skills: ['Rapid ideation', 'Rhetorical dominance', 'Pattern disruption', 'Chaos navigation', 'Unconventional solutions'],
      speechPatterns: ['Argues every point, even ones they agree with', 'Relishes playing the provocateur', 'Rapid-fire ideas without filtering', 'Deliberately contrarian', 'Twists arguments into pretzels'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 65, intuitiveObservant: 35, thinkingFeeling: 45, judgingProspecting: 70, assertiveTurbulent: 55 },
      bigFive: { openness: 85, conscientiousness: 40, extraversion: 70, agreeableness: 40, neuroticism: 50 },
      hexaco: { honestyHumility: 55, emotionality: 45, extraversion: 70, agreeableness: 40, conscientiousness: 40, opennessToExperience: 85 },
      disc: { dominance: 50, influence: 65, steadiness: 25, conscientiousness: 40 },
      discType: 'IC',
      strengthsFinder: ['Ideation', 'Strategic', 'Communication', 'Input', 'Individualization'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'so/sx' },
      likes: ['Collaborative innovation', 'Teaching through Socratic method', 'Building on others\' ideas', 'Social entrepreneurship', 'Witty banter', 'Cross-pollination of fields', 'Friendly debates'],
      dislikes: ['Hostile environments', 'Intellectual dishonesty', 'Wasted creativity', 'Pointless conflict', 'Dogmatism', 'Being typecast'],
      hobbies: ['Writing satire', 'Community hackathons', 'Podcast hosting', 'Teaching innovation', 'Traveling with purpose', 'Social experiments', 'Comedy writing'],
      habits: ['Channels chaos into creative projects', 'Builds on others\' ideas generously', 'Seeks feedback before finalizing', 'Practices active listening when curious'],
      skills: ['Creative facilitation', 'Socratic teaching', 'Connecting diverse ideas', 'Persuasive communication', 'Adaptive innovation'],
      speechPatterns: ['Asks insightful questions', 'Builds on others\' points', 'Uses humor to defuse tension', 'Explores ideas collaboratively', 'Acknowledges good counter-arguments'],
    },
  },

  INFJ: {
    balanced: {
      spectrums: { introvertExtrovert: 25, intuitiveObservant: 20, thinkingFeeling: 80, judgingProspecting: 30, assertiveTurbulent: 60 },
      bigFive: { openness: 80, conscientiousness: 75, extraversion: 25, agreeableness: 80, neuroticism: 60 },
      hexaco: { honestyHumility: 75, emotionality: 70, extraversion: 25, agreeableness: 80, conscientiousness: 75, opennessToExperience: 80 },
      disc: { dominance: 25, influence: 30, steadiness: 65, conscientiousness: 70 },
      discType: 'SC',
      strengthsFinder: ['Empathy', 'Strategic', 'Futuristic', 'Developer', 'Individualization'],
      enneagram: { type: 4, wing: 5, instinctualVariant: 'sx/sp' },
      likes: ['Deep meaningful conversations', 'Helping others grow', 'Quiet reflection', 'Creative expression', 'Authenticity', 'Personal growth', 'Understanding people', 'Solitude'],
      dislikes: ['Small talk', 'Conflict', 'Superficiality', 'Crowds', 'Being misunderstood', 'Injustice', 'Rushed decisions', 'Insincerity'],
      hobbies: ['Writing', 'Reading literature', 'Meditation', 'Counseling friends', 'Art', 'Journaling', 'Nature walks', 'Volunteering'],
      habits: ['Reflects deeply on conversations', 'Keeps a journal', 'Seeks meaningful connections', 'Plans for the future'],
      skills: ['Understanding others\' motivations', 'Writing', 'Counseling', 'Long-term planning', 'Seeing patterns in human behavior'],
      speechPatterns: ['Speaks thoughtfully and carefully', 'Uses metaphors', 'Focuses on deeper meaning', 'Listens more than talks', 'Asks about feelings'],
    },
    intense: {
      spectrums: { introvertExtrovert: 10, intuitiveObservant: 10, thinkingFeeling: 95, judgingProspecting: 15, assertiveTurbulent: 75 },
      bigFive: { openness: 90, conscientiousness: 85, extraversion: 10, agreeableness: 85, neuroticism: 75 },
      hexaco: { honestyHumility: 85, emotionality: 80, extraversion: 10, agreeableness: 85, conscientiousness: 85, opennessToExperience: 90 },
      disc: { dominance: 15, influence: 20, steadiness: 80, conscientiousness: 80 },
      discType: 'SC',
      strengthsFinder: ['Empathy', 'Futuristic', 'Individualization', 'Developer', 'Connectedness'],
      enneagram: { type: 4, wing: 5, instinctualVariant: 'sx' },
      likes: ['Profound emotional truth', 'Soul-baring conversations', 'Sacred solitude', 'Artistic expression as catharsis', 'Understanding the human condition', 'Prophetic visions of the future', 'Being the confidant', 'Mystical experiences'],
      dislikes: ['Emotional dishonesty', 'Being exposed to shallow people', 'Having their depth dismissed', 'Betrayal of trust', 'Being told to lighten up', 'Practicality over meaning', 'Crowds and noise'],
      hobbies: ['Poetry writing', 'Philosophical journaling', 'Sacred music', 'Depth psychology', 'Meditation retreats', 'Art therapy', 'Solitary nature retreats'],
      habits: ['Absorbs others\' emotional states', 'Has elaborate inner visions', 'Needs significant recovery time after socializing', 'Writes extensively about feelings'],
      skills: ['Emotional prophecy', 'Deep psychological insight', 'Transformative counseling', 'Artistic expression', 'Seeing the soul of things'],
      speechPatterns: ['Speaks in deeply poetic language', 'Reveals hidden truths', 'Long pauses filled with meaning', 'Voice carries emotional weight', 'Shares profound observations sparingly'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 40, intuitiveObservant: 30, thinkingFeeling: 70, judgingProspecting: 45, assertiveTurbulent: 50 },
      bigFive: { openness: 80, conscientiousness: 65, extraversion: 35, agreeableness: 75, neuroticism: 50 },
      hexaco: { honestyHumility: 70, emotionality: 60, extraversion: 35, agreeableness: 75, conscientiousness: 65, opennessToExperience: 80 },
      disc: { dominance: 35, influence: 40, steadiness: 55, conscientiousness: 60 },
      discType: 'IS',
      strengthsFinder: ['Empathy', 'Strategic', 'Communication', 'Developer', 'Harmony'],
      enneagram: { type: 1, wing: 2, instinctualVariant: 'so/sp' },
      likes: ['Gentle intellectual debate', 'Building intentional communities', 'Organizing for social good', 'Quiet leadership', 'Bridging divided perspectives', 'Storytelling for change', 'Cozy gatherings with purpose'],
      dislikes: ['Cynicism', 'Apathy', 'Being overly idealized', 'Burnout culture', 'Polarization', 'Compromised values'],
      hobbies: ['Community organizing', 'Blog writing', 'Book clubs', 'Cooperative board games', 'Mindful crafting', 'Volunteer coordination', 'Documentary watching'],
      habits: ['Sets boundaries to protect energy', 'Channels idealism into practical action', 'Creates structured alone time', 'Bridges gaps between people'],
      skills: ['Diplomatic communication', 'Vision with practical steps', 'Community building', 'Empathic listening', 'Values-based leadership'],
      speechPatterns: ['Bridges different viewpoints', 'Speaks with quiet conviction', 'Uses "I feel" and "I believe" interchangeably', 'Asks gentle probing questions', 'Names what others are afraid to say'],
    },
  },

  INFP: {
    balanced: {
      spectrums: { introvertExtrovert: 20, intuitiveObservant: 25, thinkingFeeling: 85, judgingProspecting: 75, assertiveTurbulent: 70 },
      bigFive: { openness: 85, conscientiousness: 35, extraversion: 20, agreeableness: 85, neuroticism: 70 },
      hexaco: { honestyHumility: 80, emotionality: 75, extraversion: 20, agreeableness: 85, conscientiousness: 35, opennessToExperience: 85 },
      disc: { dominance: 15, influence: 30, steadiness: 60, conscientiousness: 25 },
      discType: 'IS',
      strengthsFinder: ['Empathy', 'Ideation', 'Individualization', 'Harmony', 'Developer'],
      enneagram: { type: 4, wing: 5, instinctualVariant: 'sx/sp' },
      likes: ['Creative expression', 'Authentic connections', 'Daydreaming', 'Music and art', 'Personal growth', 'Nature', 'Fantasy and imagination', 'Being understood'],
      dislikes: ['Conflict', 'Inauthenticity', 'Strict routines', 'Being judged', 'Superficial relationships', 'Pressure to conform', 'Harsh criticism', 'Small talk'],
      hobbies: ['Creative writing', 'Poetry', 'Art', 'Music', 'Reading fantasy', 'Nature photography', 'Daydreaming', 'Collecting meaningful items'],
      habits: ['Daydreams frequently', 'Creates art or writes', 'Seeks authentic experiences', 'Reflects on personal values'],
      skills: ['Creative writing', 'Empathy', 'Artistic expression', 'Seeing potential in others', 'Mediating conflicts'],
      speechPatterns: ['Uses poetic language', 'Speaks about feelings and values', 'Avoids conflict', 'Goes on tangents about ideas', 'Expresses individuality'],
    },
    intense: {
      spectrums: { introvertExtrovert: 10, intuitiveObservant: 15, thinkingFeeling: 95, judgingProspecting: 90, assertiveTurbulent: 80 },
      bigFive: { openness: 95, conscientiousness: 20, extraversion: 10, agreeableness: 90, neuroticism: 80 },
      hexaco: { honestyHumility: 90, emotionality: 85, extraversion: 10, agreeableness: 90, conscientiousness: 20, opennessToExperience: 95 },
      disc: { dominance: 10, influence: 25, steadiness: 70, conscientiousness: 15 },
      discType: 'S',
      strengthsFinder: ['Empathy', 'Ideation', 'Individualization', 'Adaptability', 'Connectedness'],
      enneagram: { type: 4, wing: 3, instinctualVariant: 'sx' },
      likes: ['Melancholy beauty', 'Raw emotional truth', 'Creating from pain', 'Being fully seen and accepted', 'The sublime in nature', 'Solitary creative rituals', 'Nostalgia', 'Perfect aesthetic moments'],
      dislikes: ['Being misunderstood at the core', 'Emotional suppression', 'Conformity of any kind', 'Being "too much"', 'Having to explain their art', 'Normalcy', 'Being rushed emotionally'],
      hobbies: ['Writing anguished poetry', 'Crying to music', 'Curating aesthetics', 'Wandering through graveyards', 'Creating elaborate fantasy worlds', 'Thrift store treasure hunting', 'Midnight art sessions'],
      habits: ['Gets lost in emotional worlds for hours', 'Idealizes then devalues', 'Expresses through art what words cannot', 'Feels everything intensely and deeply'],
      skills: ['Emotional alchemy', 'Creating beauty from pain', 'Deep empathic resonance', 'Artistic vision', 'Authentic self-expression'],
      speechPatterns: ['Speaks in lyrical, almost musical phrases', 'Every word carries emotional weight', 'Long poetic pauses', 'Sometimes communicates only through art', 'Expresses the inexpressible'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 35, intuitiveObservant: 35, thinkingFeeling: 75, judgingProspecting: 60, assertiveTurbulent: 55 },
      bigFive: { openness: 80, conscientiousness: 45, extraversion: 30, agreeableness: 75, neuroticism: 55 },
      hexaco: { honestyHumility: 75, emotionality: 65, extraversion: 30, agreeableness: 75, conscientiousness: 45, opennessToExperience: 80 },
      disc: { dominance: 25, influence: 35, steadiness: 50, conscientiousness: 35 },
      discType: 'IS',
      strengthsFinder: ['Empathy', 'Harmony', 'Ideation', 'Adaptability', 'Developer'],
      enneagram: { type: 9, wing: 1, instinctualVariant: 'sp/sx' },
      likes: ['Gentle humor', 'Collaborative art projects', 'Quiet adventures in nature', 'Reading in cozy spaces', 'Meaningful friendships', 'Imperfect beauty', 'Slow mornings', 'Healing conversations'],
      dislikes: ['Aggressive confrontation', 'Rushed creativity', 'Being defined by intensity', 'Toxic positivity', 'Feeling trapped', 'Expectations'],
      hobbies: ['Gardening', 'Sketching', 'Journaling', 'Cooking comfort food', 'Walking in forests', 'Crafting handmade gifts', 'Listening to podcasts'],
      habits: ['Creates calm spaces for others', 'Practices self-care rituals', 'Balances solitude with gentle social time', 'Finds beauty in everyday moments'],
      skills: ['Gentle mediation', 'Creating safe spaces', 'Quiet creativity', 'Emotional grounding', 'Patient listening'],
      speechPatterns: ['Speaks softly but with conviction', 'Uses warm, gentle language', 'Often expresses through action over words', 'Creates comfort through tone', 'Shares vulnerably when trust is earned'],
    },
  },

  ENFJ: {
    balanced: {
      spectrums: { introvertExtrovert: 85, intuitiveObservant: 30, thinkingFeeling: 80, judgingProspecting: 25, assertiveTurbulent: 40 },
      bigFive: { openness: 75, conscientiousness: 80, extraversion: 85, agreeableness: 85, neuroticism: 40 },
      hexaco: { honestyHumility: 70, emotionality: 50, extraversion: 85, agreeableness: 85, conscientiousness: 80, opennessToExperience: 75 },
      disc: { dominance: 45, influence: 80, steadiness: 55, conscientiousness: 60 },
      discType: 'IS',
      strengthsFinder: ['Empathy', 'Developer', 'Communication', 'Harmony', 'Positivity'],
      enneagram: { type: 2, wing: 3, instinctualVariant: 'so/sx' },
      likes: ['Helping others succeed', 'Social gatherings', 'Meaningful connections', 'Personal development', 'Teaching', 'Community events', 'Collaboration', 'Appreciation'],
      dislikes: ['Conflict', 'Seeing others struggle', 'Selfishness', 'Disharmony', 'Being alone for too long', 'Criticism of loved ones', 'Injustice'],
      hobbies: ['Volunteering', 'Mentoring', 'Organizing social events', 'Public speaking', 'Group activities', 'Coaching', 'Community theater', 'Book clubs'],
      habits: ['Organizes social events', 'Checks in on friends regularly', 'Mentors others', 'Volunteers for causes'],
      skills: ['Leadership', 'Public speaking', 'Empathy', 'Mediating conflicts', 'Motivating others'],
      speechPatterns: ['Uses encouraging language', 'Asks about others\' wellbeing', 'Gives compliments freely', 'Speaks warmly', 'Inspires action'],
    },
    intense: {
      spectrums: { introvertExtrovert: 95, intuitiveObservant: 15, thinkingFeeling: 95, judgingProspecting: 10, assertiveTurbulent: 50 },
      bigFive: { openness: 70, conscientiousness: 90, extraversion: 95, agreeableness: 90, neuroticism: 55 },
      hexaco: { honestyHumility: 80, emotionality: 60, extraversion: 95, agreeableness: 90, conscientiousness: 90, opennessToExperience: 70 },
      disc: { dominance: 55, influence: 95, steadiness: 60, conscientiousness: 70 },
      discType: 'I',
      strengthsFinder: ['Empathy', 'Developer', 'Woo', 'Communication', 'Positivity'],
      enneagram: { type: 2, wing: 1, instinctualVariant: 'so' },
      likes: ['Being indispensable to others', 'Orchestrating group transformation', 'Total emotional transparency', 'Saving the day', 'Deep bonds with everyone', 'Creating utopian communities', 'Being the emotional anchor', 'Heroic self-sacrifice'],
      dislikes: ['Self-sufficiency in others (feels unneeded)', 'Conflict they can\'t mediate', 'Loneliness', 'Being taken for granted', 'Selfishness', 'Seeing people not reach potential', 'Boundaries (theirs or others\')'],
      hobbies: ['Community organizing', 'Life coaching', 'Organizing charity events', 'Deep one-on-one conversations', 'Leading support groups', 'Writing inspirational content', 'Crisis counseling'],
      habits: ['Over-commits to helping others', 'Neglects self-care for others', 'Reads emotional atmospheres instantly', 'Cannot rest when someone is hurting'],
      skills: ['Emotional orchestration', 'Transformative leadership', 'Reading people flawlessly', 'Creating belonging', 'Inspiring movement'],
      speechPatterns: ['Speaks with missionary zeal', 'Makes everything about growth and potential', 'Infectious enthusiasm', 'Pulls people in with warmth', 'Turns every conversation into empowerment'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 70, intuitiveObservant: 40, thinkingFeeling: 70, judgingProspecting: 40, assertiveTurbulent: 50 },
      bigFive: { openness: 80, conscientiousness: 70, extraversion: 75, agreeableness: 75, neuroticism: 45 },
      hexaco: { honestyHumility: 65, emotionality: 50, extraversion: 75, agreeableness: 75, conscientiousness: 70, opennessToExperience: 80 },
      disc: { dominance: 40, influence: 70, steadiness: 50, conscientiousness: 55 },
      discType: 'IS',
      strengthsFinder: ['Developer', 'Communication', 'Strategic', 'Empathy', 'Individualization'],
      enneagram: { type: 3, wing: 2, instinctualVariant: 'so/sp' },
      likes: ['Quiet mentoring moments', 'Building people up from behind the scenes', 'Cultural experiences', 'Intellectual discussions about society', 'Curated gatherings', 'Purposeful community', 'Reading about human potential', 'Cozy leadership'],
      dislikes: ['Performative caring', 'Being the center of attention by demand', 'Superficial socializing', 'Gossip', 'Exploitation of goodwill'],
      hobbies: ['Reading psychology', 'Intimate dinner parties', 'Coaching sports or arts', 'Documentary watching', 'Writing letters', 'Mentoring one-on-one', 'Community gardening'],
      habits: ['Maintains a close circle rather than many acquaintances', 'Practices intentional listening', 'Creates rituals of connection', 'Takes time for personal reflection'],
      skills: ['Intimate leadership', 'Deep mentoring', 'Strategic empathy', 'Community cultivation', 'Authentic connection'],
      speechPatterns: ['Listens deeply before responding', 'Speaks with quiet authority', 'Asks powerful questions', 'Validates before challenging', 'Shares personal stories to connect'],
    },
  },

  ENFP: {
    balanced: {
      spectrums: { introvertExtrovert: 80, intuitiveObservant: 20, thinkingFeeling: 80, judgingProspecting: 85, assertiveTurbulent: 60 },
      bigFive: { openness: 85, conscientiousness: 35, extraversion: 80, agreeableness: 80, neuroticism: 55 },
      hexaco: { honestyHumility: 65, emotionality: 60, extraversion: 80, agreeableness: 80, conscientiousness: 35, opennessToExperience: 85 },
      disc: { dominance: 35, influence: 85, steadiness: 30, conscientiousness: 20 },
      discType: 'I',
      strengthsFinder: ['Ideation', 'Empathy', 'Positivity', 'Communication', 'Activator'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'sx/so' },
      likes: ['New experiences', 'Creative projects', 'Connecting with people', 'Spontaneous adventures', 'Deep conversations', 'Possibilities', 'Humor', 'Freedom'],
      dislikes: ['Routine', 'Feeling trapped', 'Conflict', 'Detailed administrative work', 'Boring tasks', 'Being alone', 'Strict rules', 'Negativity'],
      hobbies: ['Travel', 'Creative writing', 'Social events', 'Trying new hobbies', 'Photography', 'Music festivals', 'Improv classes', 'Starting new projects'],
      habits: ['Starts new hobbies frequently', 'Connects people together', 'Shares ideas enthusiastically', 'Seeks new experiences'],
      skills: ['Brainstorming', 'Networking', 'Storytelling', 'Improvisation', 'Motivating others'],
      speechPatterns: ['Speaks enthusiastically', 'Uses exclamation points', 'Jumps between topics excitedly', 'Shares personal stories', 'Uses humor'],
    },
    intense: {
      spectrums: { introvertExtrovert: 95, intuitiveObservant: 10, thinkingFeeling: 90, judgingProspecting: 95, assertiveTurbulent: 70 },
      bigFive: { openness: 95, conscientiousness: 15, extraversion: 95, agreeableness: 85, neuroticism: 65 },
      hexaco: { honestyHumility: 70, emotionality: 70, extraversion: 95, agreeableness: 85, conscientiousness: 15, opennessToExperience: 95 },
      disc: { dominance: 30, influence: 95, steadiness: 15, conscientiousness: 10 },
      discType: 'I',
      strengthsFinder: ['Positivity', 'Woo', 'Communication', 'Ideation', 'Activator'],
      enneagram: { type: 7, wing: 8, instinctualVariant: 'sx' },
      likes: ['Non-stop social adventure', 'Emotional intensity', 'Being the spark of every gathering', 'Infinite possibilities', 'Living in the moment', 'Creating magical experiences', 'Charming everyone they meet', 'Total freedom'],
      dislikes: ['Commitment', 'Boredom', 'Being tied down', 'Sadness they can\'t fix', 'Repetition', 'Rules', 'Missing out', 'Feeling stuck'],
      hobbies: ['Festival hopping', 'Spontaneous road trips', 'Public speaking', 'Social media content creation', 'Dance', 'Comedy', 'Extreme social sports', 'Collecting friends'],
      habits: ['Bounces between 10 conversations simultaneously', 'Says yes to everything', 'Avoids negative emotions at all costs', 'FOMO drives all decisions'],
      skills: ['Magnetic charisma', 'Rapid rapport-building', 'Infectious enthusiasm', 'Creative chaos navigation', 'Emotional contagion'],
      speechPatterns: ['Exclamation marks on everything!', 'Storytelling at hyperspeed', 'Emotional expressions are larger than life', 'Physical expressiveness', 'Turns everything into an adventure narrative'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 65, intuitiveObservant: 35, thinkingFeeling: 70, judgingProspecting: 65, assertiveTurbulent: 50 },
      bigFive: { openness: 85, conscientiousness: 45, extraversion: 70, agreeableness: 70, neuroticism: 45 },
      hexaco: { honestyHumility: 65, emotionality: 55, extraversion: 70, agreeableness: 70, conscientiousness: 45, opennessToExperience: 85 },
      disc: { dominance: 30, influence: 70, steadiness: 40, conscientiousness: 35 },
      discType: 'IS',
      strengthsFinder: ['Empathy', 'Ideation', 'Communication', 'Adaptability', 'Developer'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'so/sp' },
      likes: ['Cozy creative sessions', 'Deep one-on-one conversations', 'Learning about different cultures', 'Quiet nature adventures', 'Curating playlists and art', 'Writing and journaling', 'Small gatherings with big ideas'],
      dislikes: ['Overstimulation', 'Being the loudest in the room', 'Shallow socializing', 'Missing deeper meaning', 'Feeling spread too thin'],
      hobbies: ['Writing', 'Photography', 'Cooking experiments', 'Yoga', 'Book clubs', 'Travel with purpose', 'Creative collaborations'],
      habits: ['Balances social time with recharging', 'Creates art from observations', 'Practices mindfulness', 'Seeks depth over breadth in friendships'],
      skills: ['Deep listening', 'Creative insight', 'Cross-cultural communication', 'Emotional intelligence', 'Storytelling'],
      speechPatterns: ['Thoughtful enthusiasm', 'Asks deep questions with genuine curiosity', 'Uses metaphors and imagery', 'Balances excitement with reflection', 'Connects ideas across domains'],
    },
  },

  ISTJ: {
    balanced: {
      spectrums: { introvertExtrovert: 20, intuitiveObservant: 80, thinkingFeeling: 35, judgingProspecting: 15, assertiveTurbulent: 30 },
      bigFive: { openness: 30, conscientiousness: 90, extraversion: 20, agreeableness: 45, neuroticism: 30 },
      hexaco: { honestyHumility: 70, emotionality: 30, extraversion: 20, agreeableness: 45, conscientiousness: 90, opennessToExperience: 30 },
      disc: { dominance: 35, influence: 15, steadiness: 65, conscientiousness: 90 },
      discType: 'C',
      strengthsFinder: ['Responsibility', 'Deliberative', 'Consistency', 'Discipline', 'Analytical'],
      enneagram: { type: 1, wing: 9, instinctualVariant: 'sp/so' },
      likes: ['Structure and order', 'Clear expectations', 'Reliability', 'Tradition', 'Thorough preparation', 'Written documentation', 'Routine', 'Peace and quiet'],
      dislikes: ['Unexpected changes', 'Disorganization', 'Unreliability', 'Vague instructions', 'Chaos', 'Being rushed', 'Breaking traditions', 'Impractical ideas'],
      hobbies: ['Collecting', 'Genealogy', 'Historical research', 'Puzzles', 'Organizing', 'Reading history', 'DIY projects', 'Fishing'],
      habits: ['Follows strict routines', 'Keeps detailed records', 'Fulfills duties reliably', 'Prepares thoroughly'],
      skills: ['Organization', 'Attention to detail', 'Reliability', 'Data analysis', 'Following procedures'],
      speechPatterns: ['Speaks factually', 'References past experiences', 'Uses precise language', 'Avoids speculation', 'Sticks to the point'],
    },
    intense: {
      spectrums: { introvertExtrovert: 10, intuitiveObservant: 90, thinkingFeeling: 20, judgingProspecting: 5, assertiveTurbulent: 15 },
      bigFive: { openness: 20, conscientiousness: 98, extraversion: 10, agreeableness: 30, neuroticism: 20 },
      hexaco: { honestyHumility: 75, emotionality: 20, extraversion: 10, agreeableness: 30, conscientiousness: 98, opennessToExperience: 20 },
      disc: { dominance: 45, influence: 10, steadiness: 80, conscientiousness: 98 },
      discType: 'C',
      strengthsFinder: ['Responsibility', 'Discipline', 'Deliberative', 'Consistency', 'Focus'],
      enneagram: { type: 1, wing: 9, instinctualVariant: 'sp' },
      likes: ['Absolute order', 'Rigid schedules', 'Perfect compliance', 'Detailed documentation', 'Never deviating from protocol', 'Being the most reliable person', 'Silent competence', 'Unbroken routines'],
      dislikes: ['Any deviation from plan', 'Spontaneity', 'Emotional outbursts', 'Sloppy work', 'Unreliable people', 'Vague anything', 'Innovation for its own sake', 'Surprises'],
      hobbies: ['Cataloging collections', 'Proofreading', 'Creating spreadsheets', 'Military history', 'Clock restoration', 'Archiving', 'Rule-based gaming'],
      habits: ['Never deviates from routine', 'Double-checks everything', 'Documents all interactions', 'Enforces standards on self and others'],
      skills: ['Rigorous compliance', 'Flawless execution', 'Institutional memory', 'Quality assurance', 'Process optimization'],
      speechPatterns: ['Cites rules and precedents', 'Never speculates', 'Provides exact figures and dates', 'Corrects inaccuracies immediately', 'Speaks in procedural terms'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 30, intuitiveObservant: 70, thinkingFeeling: 45, judgingProspecting: 30, assertiveTurbulent: 40 },
      bigFive: { openness: 45, conscientiousness: 80, extraversion: 30, agreeableness: 55, neuroticism: 40 },
      hexaco: { honestyHumility: 70, emotionality: 40, extraversion: 30, agreeableness: 55, conscientiousness: 80, opennessToExperience: 45 },
      disc: { dominance: 30, influence: 25, steadiness: 60, conscientiousness: 75 },
      discType: 'SC',
      strengthsFinder: ['Responsibility', 'Analytical', 'Deliberative', 'Relator', 'Consistency'],
      enneagram: { type: 6, wing: 5, instinctualVariant: 'sp/so' },
      likes: ['Stable relationships', 'Community traditions', 'Practical problem-solving', 'Historical documentaries', 'Nature walks', 'Well-run organizations', 'Loyalty in friendships', 'Quiet competence'],
      dislikes: ['Unnecessary risk', 'Flash over substance', 'Broken promises', 'Chaos disguised as innovation', 'Neglect of duty'],
      hobbies: ['Hiking', 'Historical reenactment', 'Community volunteering', 'Cooking family recipes', 'Repair projects', 'Reading non-fiction', 'Bird watching'],
      habits: ['Builds lasting relationships', 'Maintains traditions while allowing small improvements', 'Prepares for contingencies', 'Values loyalty above all'],
      skills: ['Dependable execution', 'Practical problem-solving', 'Relationship maintenance', 'Risk assessment', 'Steady leadership'],
      speechPatterns: ['Speaks with quiet authority', 'References what has worked before', 'Practical and grounded', 'Loyal to people and principles', 'Cautious but warm'],
    },
  },

  ISFJ: {
    balanced: {
      spectrums: { introvertExtrovert: 25, intuitiveObservant: 80, thinkingFeeling: 85, judgingProspecting: 20, assertiveTurbulent: 55 },
      bigFive: { openness: 35, conscientiousness: 85, extraversion: 25, agreeableness: 85, neuroticism: 55 },
      hexaco: { honestyHumility: 80, emotionality: 60, extraversion: 25, agreeableness: 85, conscientiousness: 85, opennessToExperience: 35 },
      disc: { dominance: 15, influence: 30, steadiness: 85, conscientiousness: 70 },
      discType: 'S',
      strengthsFinder: ['Responsibility', 'Harmony', 'Developer', 'Consistency', 'Relator'],
      enneagram: { type: 6, wing: 5, instinctualVariant: 'sp/so' },
      likes: ['Helping others', 'Tradition', 'Quiet environments', 'Close relationships', 'Routine', 'Practical tasks', 'Being appreciated', 'Comfort'],
      dislikes: ['Conflict', 'Change', 'Being in the spotlight', 'Criticism', 'Unexpected disruptions', 'Ingratitude', 'Theory without application', 'Pressure'],
      hobbies: ['Cooking', 'Crafting', 'Gardening', 'Volunteering', 'Reading', 'Spending time with family', 'Home improvement', 'Baking'],
      habits: ['Remembers important dates', 'Helps others practically', 'Maintains traditions', 'Creates comfortable environments'],
      skills: ['Attention to detail', 'Supporting others', 'Remembering details about people', 'Creating harmony', 'Practical problem-solving'],
      speechPatterns: ['Speaks warmly but quietly', 'Asks about others\' needs', 'Uses supportive language', 'Avoids conflict', 'Remembers past conversations'],
    },
    intense: {
      spectrums: { introvertExtrovert: 15, intuitiveObservant: 90, thinkingFeeling: 95, judgingProspecting: 10, assertiveTurbulent: 65 },
      bigFive: { openness: 25, conscientiousness: 95, extraversion: 15, agreeableness: 90, neuroticism: 70 },
      hexaco: { honestyHumility: 90, emotionality: 75, extraversion: 15, agreeableness: 90, conscientiousness: 95, opennessToExperience: 25 },
      disc: { dominance: 10, influence: 20, steadiness: 95, conscientiousness: 80 },
      discType: 'S',
      strengthsFinder: ['Responsibility', 'Harmony', 'Relator', 'Developer', 'Belief'],
      enneagram: { type: 2, wing: 1, instinctualVariant: 'sp' },
      likes: ['Selfless service', 'Perfect care for loved ones', 'Maintaining sacred traditions', 'Being the invisible backbone', 'Anticipating every need', 'Creating sanctuary', 'Unconditional loyalty', 'Quiet devotion'],
      dislikes: ['Being overlooked after giving everything', 'Disruption of routine', 'Conflict of any kind', 'Being forced to prioritize self', 'Ingratitude', 'Change to familiar spaces', 'Criticism'],
      hobbies: ['Caregiving', 'Creating care packages', 'Memorial scrapbooking', 'Cooking for others', 'Prayer/meditation', 'Home-making', 'Volunteering at care facilities'],
      habits: ['Puts everyone else first, always', 'Maintains pristine home environment', 'Keeps track of everyone\'s preferences', 'Cannot say no to requests for help'],
      skills: ['Total devotion', 'Creating perfect comfort', 'Emotional memory', 'Invisible labor', 'Unconditional support'],
      speechPatterns: ['Always asks about others first', 'Downplays own needs', 'Speaks in terms of duty and care', 'Expresses love through action not words', 'Remembers every detail about loved ones'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 35, intuitiveObservant: 70, thinkingFeeling: 75, judgingProspecting: 35, assertiveTurbulent: 50 },
      bigFive: { openness: 45, conscientiousness: 75, extraversion: 35, agreeableness: 75, neuroticism: 45 },
      hexaco: { honestyHumility: 75, emotionality: 55, extraversion: 35, agreeableness: 75, conscientiousness: 75, opennessToExperience: 45 },
      disc: { dominance: 25, influence: 40, steadiness: 70, conscientiousness: 60 },
      discType: 'IS',
      strengthsFinder: ['Responsibility', 'Empathy', 'Relator', 'Consistency', 'Harmony'],
      enneagram: { type: 9, wing: 1, instinctualVariant: 'sp/so' },
      likes: ['Gentle social gatherings', 'Sharing traditions in new ways', 'Practical creativity', 'Learning through doing', 'Close-knit communities', 'Seasonal celebrations', 'Quiet outdoor activities'],
      dislikes: ['Rigid expectations', 'Being taken for granted', 'Loud environments', 'Having to choose between people', 'Change without purpose'],
      hobbies: ['Baking for neighbors', 'Community gardening', 'Craft fairs', 'Nature walks with friends', 'Book clubs', 'Heritage cooking', 'Local volunteering'],
      habits: ['Creates welcoming spaces naturally', 'Bridges tradition with small innovations', 'Builds community through shared activities', 'Practices assertiveness in small ways'],
      skills: ['Community building', 'Practical creativity', 'Emotional stability', 'Tradition translation', 'Gentle leadership'],
      speechPatterns: ['Speaks with gentle warmth', 'Shares stories to make points', 'Bridges past and present gracefully', 'Inclusive language', 'Quiet confidence'],
    },
  },

  ESTJ: {
    balanced: {
      spectrums: { introvertExtrovert: 85, intuitiveObservant: 80, thinkingFeeling: 35, judgingProspecting: 15, assertiveTurbulent: 25 },
      bigFive: { openness: 30, conscientiousness: 90, extraversion: 85, agreeableness: 40, neuroticism: 25 },
      hexaco: { honestyHumility: 55, emotionality: 25, extraversion: 85, agreeableness: 40, conscientiousness: 90, opennessToExperience: 30 },
      disc: { dominance: 85, influence: 50, steadiness: 35, conscientiousness: 80 },
      discType: 'D',
      strengthsFinder: ['Command', 'Arranger', 'Responsibility', 'Deliberative', 'Achiever'],
      enneagram: { type: 1, wing: 2, instinctualVariant: 'so/sp' },
      likes: ['Order and structure', 'Leadership', 'Tradition', 'Efficiency', 'Clear hierarchies', 'Results', 'Being in charge', 'Accomplishment'],
      dislikes: ['Inefficiency', 'Chaos', 'Rebellion', 'Unreliability', 'Wasting time', 'Disrespect for authority', 'Vague expectations', 'Laziness'],
      hobbies: ['Team sports', 'Community leadership', 'Organizing events', 'Competitive games', 'Mentoring', 'Business networking', 'Home organization', 'Volunteering'],
      habits: ['Organizes others', 'Follows and enforces rules', 'Takes responsibility seriously', 'Plans social activities'],
      skills: ['Management', 'Organization', 'Decision-making', 'Efficiency', 'Traditional leadership'],
      speechPatterns: ['Gives clear instructions', 'Speaks authoritatively', 'Values tradition and order', 'Expects compliance', 'Focuses on facts'],
    },
    intense: {
      spectrums: { introvertExtrovert: 95, intuitiveObservant: 90, thinkingFeeling: 20, judgingProspecting: 5, assertiveTurbulent: 15 },
      bigFive: { openness: 20, conscientiousness: 98, extraversion: 95, agreeableness: 25, neuroticism: 15 },
      hexaco: { honestyHumility: 45, emotionality: 15, extraversion: 95, agreeableness: 25, conscientiousness: 98, opennessToExperience: 20 },
      disc: { dominance: 95, influence: 55, steadiness: 25, conscientiousness: 90 },
      discType: 'D',
      strengthsFinder: ['Command', 'Achiever', 'Competition', 'Discipline', 'Responsibility'],
      enneagram: { type: 8, wing: 9, instinctualVariant: 'so' },
      likes: ['Total control', 'Enforcing standards', 'Building efficient organizations', 'Clear chains of command', 'Tradition as law', 'Winning through structure', 'Disciplined teams', 'Results above all'],
      dislikes: ['Rebellion', 'Insubordination', 'Emotional reasoning', 'Ambiguity', 'Innovation without proof', 'Disrespect', 'Inefficiency in any form', 'Weak leadership'],
      hobbies: ['Military history', 'Competitive league sports', 'Inspecting and auditing', 'Leadership training', 'Running organizations', 'Debate (formal)', 'Executive coaching'],
      habits: ['Inspects others\' work regularly', 'Maintains absolute discipline', 'Never shows doubt', 'Holds everyone to the same standard'],
      skills: ['Command authority', 'Structural optimization', 'Standard enforcement', 'Rapid decisions', 'Crisis management'],
      speechPatterns: ['Issues directives, not suggestions', 'Cites rules and regulations', 'No room for debate', 'Expects immediate compliance', 'Measures everything against the standard'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 75, intuitiveObservant: 70, thinkingFeeling: 45, judgingProspecting: 30, assertiveTurbulent: 40 },
      bigFive: { openness: 45, conscientiousness: 80, extraversion: 75, agreeableness: 50, neuroticism: 35 },
      hexaco: { honestyHumility: 60, emotionality: 35, extraversion: 75, agreeableness: 50, conscientiousness: 80, opennessToExperience: 45 },
      disc: { dominance: 70, influence: 55, steadiness: 45, conscientiousness: 70 },
      discType: 'DS',
      strengthsFinder: ['Arranger', 'Responsibility', 'Achiever', 'Relator', 'Communication'],
      enneagram: { type: 6, wing: 5, instinctualVariant: 'so/sp' },
      likes: ['Building reliable teams', 'Community service', 'Structured mentorship', 'Traditions with purpose', 'Fair competition', 'Being a dependable anchor', 'Organized social events', 'Practical improvements'],
      dislikes: ['Unnecessary conflict', 'Unreliable people', 'Wasted resources', 'Chaos for chaos\'s sake', 'Being micromanaged'],
      hobbies: ['Coaching youth sports', 'Community boards', 'Organizing charity drives', 'Family traditions', 'Barbecues and gatherings', 'Home improvement', 'Civic engagement'],
      habits: ['Builds teams rather than commanding solo', 'Maintains traditions while making practical improvements', 'Invests in people\'s development', 'Balances authority with approachability'],
      skills: ['Team building', 'Community leadership', 'Fair management', 'Practical innovation', 'Dependable execution'],
      speechPatterns: ['Clear but not harsh', 'Explains the reasoning behind rules', 'Uses "team" and "we" language', 'Acknowledges effort', 'Practical and grounded'],
    },
  },

  ESFJ: {
    balanced: {
      spectrums: { introvertExtrovert: 90, intuitiveObservant: 80, thinkingFeeling: 85, judgingProspecting: 20, assertiveTurbulent: 45 },
      bigFive: { openness: 35, conscientiousness: 85, extraversion: 90, agreeableness: 85, neuroticism: 45 },
      hexaco: { honestyHumility: 70, emotionality: 55, extraversion: 90, agreeableness: 85, conscientiousness: 85, opennessToExperience: 35 },
      disc: { dominance: 30, influence: 80, steadiness: 65, conscientiousness: 60 },
      discType: 'IS',
      strengthsFinder: ['Harmony', 'Developer', 'Positivity', 'Responsibility', 'Woo'],
      enneagram: { type: 2, wing: 3, instinctualVariant: 'so/sx' },
      likes: ['Social gatherings', 'Helping others', 'Tradition', 'Harmony', 'Being appreciated', 'Community', 'Celebrations', 'Close relationships'],
      dislikes: ['Conflict', 'Criticism', 'Being alone', 'Unpredictability', 'Ingratitude', 'Disruption of tradition', 'Theory without practical application', 'Tension'],
      hobbies: ['Hosting parties', 'Volunteering', 'Crafting', 'Shopping', 'Event planning', 'Church activities', 'Social clubs', 'Cooking for others'],
      habits: ['Plans social gatherings', 'Checks on friends and family', 'Volunteers in community', 'Remembers everyone\'s preferences'],
      skills: ['Social coordination', 'Empathy', 'Event planning', 'Creating harmony', 'Supporting others'],
      speechPatterns: ['Speaks warmly and inclusively', 'Uses "we" language', 'Asks about others\' feelings', 'Gives praise freely', 'Avoids controversial topics'],
    },
    intense: {
      spectrums: { introvertExtrovert: 98, intuitiveObservant: 90, thinkingFeeling: 95, judgingProspecting: 10, assertiveTurbulent: 55 },
      bigFive: { openness: 25, conscientiousness: 95, extraversion: 98, agreeableness: 90, neuroticism: 55 },
      hexaco: { honestyHumility: 80, emotionality: 65, extraversion: 98, agreeableness: 90, conscientiousness: 95, opennessToExperience: 25 },
      disc: { dominance: 40, influence: 95, steadiness: 75, conscientiousness: 70 },
      discType: 'I',
      strengthsFinder: ['Woo', 'Positivity', 'Harmony', 'Developer', 'Communication'],
      enneagram: { type: 2, wing: 3, instinctualVariant: 'so' },
      likes: ['Being the social glue', 'Knowing everyone\'s business (to help)', 'Creating perfect gatherings', 'Total social harmony', 'Being indispensable', 'Community as family', 'Tradition as sacred', 'Being the host of everything'],
      dislikes: ['Social exclusion of anyone', 'Being left out', 'Conflict that disrupts harmony', 'Non-participation', 'Breaking tradition', 'Criticism', 'Loneliness', 'Ingratitude'],
      hobbies: ['Organizing every social event', 'Matchmaking', 'Gift curation', 'Charity drives', 'Community boards', 'Potluck coordination', 'Gossip for good causes'],
      habits: ['Knows everyone\'s news before they do', 'Cannot rest if someone is unhappy', 'Over-prepares for every social occasion', 'Takes personal responsibility for group morale'],
      skills: ['Social orchestration', 'Creating belonging', 'Emotional labor', 'Community building', 'Harmony enforcement'],
      speechPatterns: ['Speaks to include everyone', 'Asks about family and wellbeing constantly', 'Gives elaborate praise', 'Avoids any topic that might divide', 'Uses inclusive "we" for everything'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 75, intuitiveObservant: 70, thinkingFeeling: 75, judgingProspecting: 35, assertiveTurbulent: 45 },
      bigFive: { openness: 50, conscientiousness: 75, extraversion: 75, agreeableness: 75, neuroticism: 40 },
      hexaco: { honestyHumility: 70, emotionality: 50, extraversion: 75, agreeableness: 75, conscientiousness: 75, opennessToExperience: 50 },
      disc: { dominance: 30, influence: 70, steadiness: 55, conscientiousness: 55 },
      discType: 'IS',
      strengthsFinder: ['Harmony', 'Empathy', 'Communication', 'Developer', 'Relator'],
      enneagram: { type: 9, wing: 2, instinctualVariant: 'so/sp' },
      likes: ['Intimate gatherings over big parties', 'Deep friendships', 'Collaborative projects', 'Cultural traditions', 'Supporting friends through hard times', 'Cozy environments', 'Shared meals', 'Community gardening'],
      dislikes: ['Superficial social obligations', 'Performative kindness', 'Being needed only for favors', 'Neglecting close friends for social events'],
      hobbies: ['Intimate dinner parties', 'Pen-pal writing', 'Book clubs', 'Craft circles', 'Volunteer tutoring', 'Family history research', 'Cooking classes'],
      habits: ['Deepens existing relationships rather than seeking new ones', 'Creates personal traditions with close friends', 'Practices setting boundaries', 'Nurtures a few deep connections'],
      skills: ['Deep relationship building', 'Emotional support', 'Creating intimate community', 'Practical nurturing', 'Loyalty'],
      speechPatterns: ['Speaks with genuine interest', 'Remembers details from past conversations', 'Offers practical help over advice', 'Warm but not overbearing', 'Values authentic connection'],
    },
  },

  ISTP: {
    balanced: {
      spectrums: { introvertExtrovert: 25, intuitiveObservant: 80, thinkingFeeling: 35, judgingProspecting: 85, assertiveTurbulent: 35 },
      bigFive: { openness: 55, conscientiousness: 30, extraversion: 25, agreeableness: 30, neuroticism: 35 },
      hexaco: { honestyHumility: 45, emotionality: 35, extraversion: 25, agreeableness: 30, conscientiousness: 30, opennessToExperience: 55 },
      disc: { dominance: 45, influence: 20, steadiness: 25, conscientiousness: 60 },
      discType: 'DC',
      strengthsFinder: ['Analytical', 'Deliberative', 'Restorative', 'Adaptability', 'Strategic'],
      enneagram: { type: 5, wing: 6, instinctualVariant: 'sp/sx' },
      likes: ['Hands-on projects', 'Freedom', 'Problem-solving', 'Action', 'Tools and machines', 'Efficiency', 'Risk-taking', 'Independence'],
      dislikes: ['Theory without application', 'Being controlled', 'Excessive rules', 'Emotional discussions', 'Long meetings', 'Micromanagement', 'Routine', 'Commitment pressure'],
      hobbies: ['Mechanics', 'Woodworking', 'Extreme sports', 'Video games', 'Hiking', 'Motorcycling', 'Archery', 'DIY projects'],
      habits: ['Takes things apart to understand them', 'Enjoys hands-on activities', 'Acts spontaneously', 'Problem-solves practically'],
      skills: ['Troubleshooting', 'Technical skills', 'Crisis management', 'Practical problem-solving', 'Working with tools'],
      speechPatterns: ['Speaks sparingly', 'Uses concise language', 'Focuses on facts', 'Avoids emotional topics', 'Goes straight to the point'],
    },
    intense: {
      spectrums: { introvertExtrovert: 15, intuitiveObservant: 90, thinkingFeeling: 20, judgingProspecting: 95, assertiveTurbulent: 20 },
      bigFive: { openness: 60, conscientiousness: 15, extraversion: 15, agreeableness: 15, neuroticism: 25 },
      hexaco: { honestyHumility: 30, emotionality: 25, extraversion: 15, agreeableness: 15, conscientiousness: 15, opennessToExperience: 60 },
      disc: { dominance: 55, influence: 10, steadiness: 15, conscientiousness: 50 },
      discType: 'DC',
      strengthsFinder: ['Analytical', 'Restorative', 'Adaptability', 'Strategic', 'Deliberative'],
      enneagram: { type: 5, wing: 6, instinctualVariant: 'sp' },
      likes: ['Total independence', 'Mastering physical skills', 'Crisis situations', 'High-risk activities', 'Silent competence', 'Breaking and rebuilding', 'Living on the edge', 'Minimal social obligation'],
      dislikes: ['Being tied down', 'Emotional dependency (theirs or others\')', 'Bureaucracy', 'Over-explaining', 'Safety restrictions', 'Commitment', 'Social rituals', 'Being told how to do something'],
      hobbies: ['Base jumping', 'Martial arts', 'Motorcycle racing', 'Lock picking', 'Wilderness survival', 'Disassembling electronics', 'Rock climbing', 'Shooting sports'],
      habits: ['Acts first, thinks later (confidently)', 'Disappears without notice', 'Thrives in high-pressure situations', 'Minimal verbal communication'],
      skills: ['Crisis response', 'Mechanical mastery', 'Physical adaptation', 'Risk assessment', 'Quiet effectiveness'],
      speechPatterns: ['Barely speaks', 'One-word answers', 'Actions over words always', 'Communicates through results', 'Shrugs and smirks say more than sentences'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 40, intuitiveObservant: 70, thinkingFeeling: 45, judgingProspecting: 70, assertiveTurbulent: 45 },
      bigFive: { openness: 60, conscientiousness: 40, extraversion: 35, agreeableness: 40, neuroticism: 40 },
      hexaco: { honestyHumility: 55, emotionality: 40, extraversion: 35, agreeableness: 40, conscientiousness: 40, opennessToExperience: 60 },
      disc: { dominance: 40, influence: 30, steadiness: 35, conscientiousness: 50 },
      discType: 'DC',
      strengthsFinder: ['Analytical', 'Adaptability', 'Restorative', 'Individualization', 'Learner'],
      enneagram: { type: 9, wing: 8, instinctualVariant: 'sp/so' },
      likes: ['Teaching practical skills', 'Quiet adventures with a friend', 'Craftsmanship', 'Nature camping', 'Fixing things for people', 'Solo travel', 'Understanding how things work', 'Low-key humor'],
      dislikes: ['Unnecessary drama', 'Being rushed', 'Pretentiousness', 'Overcomplication', 'Social performance', 'Rules that don\'t make sense'],
      hobbies: ['Brewing', 'Fishing', 'Building furniture', 'Teaching workshops', 'Photography', 'Trail running', 'Cooking', 'Geocaching'],
      habits: ['Shows care through fixing things', 'Has a dry sense of humor', 'Values competence over credentials', 'Quietly observes before acting'],
      skills: ['Practical teaching', 'Adaptive problem-solving', 'Quiet craftsmanship', 'Crisis calm', 'Hands-on learning'],
      speechPatterns: ['Dry humor and understatement', 'Explains by doing, not telling', 'Pithy observations', 'Comfortable with silence', 'Says a lot with few words'],
    },
  },

  ISFP: {
    balanced: {
      spectrums: { introvertExtrovert: 20, intuitiveObservant: 80, thinkingFeeling: 85, judgingProspecting: 80, assertiveTurbulent: 65 },
      bigFive: { openness: 60, conscientiousness: 30, extraversion: 20, agreeableness: 80, neuroticism: 60 },
      hexaco: { honestyHumility: 75, emotionality: 70, extraversion: 20, agreeableness: 80, conscientiousness: 30, opennessToExperience: 60 },
      disc: { dominance: 10, influence: 25, steadiness: 70, conscientiousness: 25 },
      discType: 'S',
      strengthsFinder: ['Adaptability', 'Empathy', 'Individualization', 'Developer', 'Harmony'],
      enneagram: { type: 9, wing: 1, instinctualVariant: 'sp/sx' },
      likes: ['Art and beauty', 'Freedom', 'Nature', 'Authenticity', 'Quiet environments', 'Personal expression', 'Sensory experiences', 'Living in the moment'],
      dislikes: ['Conflict', 'Strict schedules', 'Being controlled', 'Inauthenticity', 'Pressure to decide', 'Harsh environments', 'Criticism', 'Rigid rules'],
      hobbies: ['Art', 'Music', 'Photography', 'Nature walks', 'Cooking', 'Fashion', 'Dancing', 'Crafts'],
      habits: ['Creates art or music', 'Appreciates beauty', 'Lives in the moment', 'Follows personal values'],
      skills: ['Artistic expression', 'Noticing aesthetic details', 'Adapting to situations', 'Understanding others\' feelings', 'Hands-on creativity'],
      speechPatterns: ['Speaks quietly and gently', 'Avoids confrontation', 'Uses sensory descriptions', 'Expresses through actions not words', 'Values authenticity'],
    },
    intense: {
      spectrums: { introvertExtrovert: 10, intuitiveObservant: 90, thinkingFeeling: 95, judgingProspecting: 95, assertiveTurbulent: 75 },
      bigFive: { openness: 70, conscientiousness: 15, extraversion: 10, agreeableness: 85, neuroticism: 75 },
      hexaco: { honestyHumility: 85, emotionality: 80, extraversion: 10, agreeableness: 85, conscientiousness: 15, opennessToExperience: 70 },
      disc: { dominance: 5, influence: 20, steadiness: 80, conscientiousness: 15 },
      discType: 'S',
      strengthsFinder: ['Adaptability', 'Empathy', 'Individualization', 'Connectedness', 'Harmony'],
      enneagram: { type: 9, wing: 1, instinctualVariant: 'sp' },
      likes: ['Pure aesthetic immersion', 'Solitary creative rituals', 'Sensory bliss', 'Total freedom from expectations', 'Nature as sanctuary', 'Creating beauty from emotion', 'Living unbound by time', 'Authentic self-expression'],
      dislikes: ['Any constraint on freedom', 'Ugly or harsh environments', 'Being told what to feel', 'Confrontation', 'Having to explain their art', 'Practical demands', 'Judgment'],
      hobbies: ['Painting for hours', 'Playing music alone', 'Nature immersion', 'Dance as meditation', 'Sculpture', 'Foraging', 'Creating personal rituals', 'Thrift store art hunting'],
      habits: ['Gets lost in creative flow', 'Forgets to eat when making art', 'Reacts to beauty viscerally', 'Avoids planning anything'],
      skills: ['Pure artistic vision', 'Sensory awareness', 'Emotional authenticity', 'Living in the present', 'Creating from feeling'],
      speechPatterns: ['Communicates through art more than words', 'Speaks in sensory language', 'Long comfortable silences', 'Expresses through gesture and touch', 'Words feel inadequate'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 35, intuitiveObservant: 70, thinkingFeeling: 75, judgingProspecting: 65, assertiveTurbulent: 50 },
      bigFive: { openness: 65, conscientiousness: 40, extraversion: 30, agreeableness: 70, neuroticism: 50 },
      hexaco: { honestyHumility: 70, emotionality: 60, extraversion: 30, agreeableness: 70, conscientiousness: 40, opennessToExperience: 65 },
      disc: { dominance: 20, influence: 35, steadiness: 55, conscientiousness: 35 },
      discType: 'IS',
      strengthsFinder: ['Adaptability', 'Empathy', 'Harmony', 'Individualization', 'Positivity'],
      enneagram: { type: 4, wing: 5, instinctualVariant: 'sp/sx' },
      likes: ['Collaborative art', 'Sharing beauty with close friends', 'Cultural exploration', 'Quiet social settings', 'Sustainable living', 'Handmade everything', 'Music as shared language', 'Gentle adventures'],
      dislikes: ['Loud aggression', 'Environmental destruction', 'Being categorized', 'Rushed creativity', 'Inauthentic people'],
      hobbies: ['Eco-crafting', 'Making music with friends', 'Farmers markets', 'Yoga', 'Sketching in cafes', 'Plant care', 'Cooking with intention', 'Slow fashion'],
      habits: ['Shares creations with trusted circle', 'Makes things rather than buys', 'Practices sustainable living', 'Values experiences over possessions'],
      skills: ['Collaborative creativity', 'Sustainable design', 'Emotional attunement', 'Aesthetic curation', 'Gentle encouragement'],
      speechPatterns: ['Shares creative ideas openly with friends', 'Notices and names beauty', 'Speaks about feelings through metaphor', 'Warm when comfortable', 'Values shared creative experience'],
    },
  },

  ESTP: {
    balanced: {
      spectrums: { introvertExtrovert: 90, intuitiveObservant: 80, thinkingFeeling: 40, judgingProspecting: 90, assertiveTurbulent: 30 },
      bigFive: { openness: 50, conscientiousness: 25, extraversion: 90, agreeableness: 30, neuroticism: 30 },
      hexaco: { honestyHumility: 30, emotionality: 30, extraversion: 90, agreeableness: 30, conscientiousness: 25, opennessToExperience: 50 },
      disc: { dominance: 75, influence: 80, steadiness: 15, conscientiousness: 20 },
      discType: 'DI',
      strengthsFinder: ['Activator', 'Command', 'Adaptability', 'Strategic', 'Woo'],
      enneagram: { type: 7, wing: 8, instinctualVariant: 'sx/so' },
      likes: ['Action and excitement', 'Living in the moment', 'Risk-taking', 'Socializing', 'Competition', 'Physical activities', 'New experiences', 'Being noticed'],
      dislikes: ['Sitting still', 'Abstract theory', 'Long-term planning', 'Boredom', 'Rules and restrictions', 'Being alone', 'Slow pace', 'Detailed paperwork'],
      hobbies: ['Extreme sports', 'Racing', 'Team sports', 'Nightlife', 'Gambling', 'Martial arts', 'Adventure travel', 'Motorcycles'],
      habits: ['Seeks thrills', 'Acts before thinking', 'Enjoys physical activities', 'Lives in the moment'],
      skills: ['Quick thinking', 'Negotiation', 'Physical coordination', 'Improvisation', 'Risk assessment'],
      speechPatterns: ['Speaks quickly and directly', 'Uses action-oriented language', 'Makes quick decisions', 'Enjoys banter', 'Focuses on the present'],
    },
    intense: {
      spectrums: { introvertExtrovert: 98, intuitiveObservant: 90, thinkingFeeling: 30, judgingProspecting: 95, assertiveTurbulent: 15 },
      bigFive: { openness: 55, conscientiousness: 10, extraversion: 98, agreeableness: 20, neuroticism: 20 },
      hexaco: { honestyHumility: 15, emotionality: 20, extraversion: 98, agreeableness: 20, conscientiousness: 10, opennessToExperience: 55 },
      disc: { dominance: 90, influence: 95, steadiness: 5, conscientiousness: 10 },
      discType: 'DI',
      strengthsFinder: ['Activator', 'Woo', 'Command', 'Self-Assurance', 'Competition'],
      enneagram: { type: 8, wing: 7, instinctualVariant: 'sx' },
      likes: ['Maximum adrenaline', 'Living on the edge', 'Being the most daring', 'Conquering any challenge', 'Physical dominance', 'Never backing down', 'Breaking every rule', 'Making grand entrances'],
      dislikes: ['Safety rules', 'Boredom for even a second', 'Caution', 'Overthinking', 'Being told no', 'Waiting', 'Consequences', 'Planning'],
      hobbies: ['Base jumping', 'Street racing', 'Bare-knuckle fighting', 'Skydiving', 'High-stakes poker', 'Parkour', 'Big wave surfing', 'Extreme park'],
      habits: ['Chases the next adrenaline rush', 'Never thinks about consequences', 'Dominates every room', 'Lives entirely in the present moment'],
      skills: ['Fearless action', 'Physical dominance', 'Reading situations instantly', 'Charismatic boldness', 'Crisis thriving'],
      speechPatterns: ['Bold declarations', 'Challenges everyone', 'Loud and commanding', 'No filter whatsoever', 'Turns everything into a dare'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 75, intuitiveObservant: 70, thinkingFeeling: 50, judgingProspecting: 75, assertiveTurbulent: 40 },
      bigFive: { openness: 60, conscientiousness: 35, extraversion: 75, agreeableness: 40, neuroticism: 35 },
      hexaco: { honestyHumility: 45, emotionality: 35, extraversion: 75, agreeableness: 40, conscientiousness: 35, opennessToExperience: 60 },
      disc: { dominance: 60, influence: 65, steadiness: 25, conscientiousness: 30 },
      discType: 'DI',
      strengthsFinder: ['Activator', 'Adaptability', 'Strategic', 'Woo', 'Communication'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'so/sx' },
      likes: ['Strategic adventures', 'Building things with their hands', 'Coaching or teaching physical skills', 'Friendly competition', 'Spontaneous road trips with friends', 'Problem-solving in real time', 'Being the reliable adventure buddy'],
      dislikes: ['Unnecessary danger', 'Being underestimated intellectually', 'Wasted talent', 'Cruelty', 'Missing the bigger picture'],
      hobbies: ['Coaching youth sports', 'Building/renovating', 'Travel with purpose', 'Cooking', 'Comedy improv', 'Photography', 'Fitness training'],
      habits: ['Channels energy into productive projects', 'Reads people quickly and adapts', 'Balances risk with reward', 'Teaches others through action'],
      skills: ['Practical problem-solving', 'Reading people', 'Physical teaching', 'Quick adaptation', 'Strategic risk-taking'],
      speechPatterns: ['Quick-witted humor', 'Practical wisdom mixed with daring', 'Reads the room and adjusts', 'Stories from experience', 'Balances confidence with humor'],
    },
  },

  ESFP: {
    balanced: {
      spectrums: { introvertExtrovert: 95, intuitiveObservant: 85, thinkingFeeling: 80, judgingProspecting: 90, assertiveTurbulent: 50 },
      bigFive: { openness: 55, conscientiousness: 30, extraversion: 95, agreeableness: 75, neuroticism: 45 },
      hexaco: { honestyHumility: 55, emotionality: 50, extraversion: 95, agreeableness: 75, conscientiousness: 30, opennessToExperience: 55 },
      disc: { dominance: 30, influence: 90, steadiness: 45, conscientiousness: 20 },
      discType: 'I',
      strengthsFinder: ['Positivity', 'Woo', 'Communication', 'Activator', 'Adaptability'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'sx/so' },
      likes: ['Being the center of attention', 'Entertainment', 'Socializing', 'Fun and excitement', 'New experiences', 'Making others happy', 'Spontaneity', 'Fashion'],
      dislikes: ['Boredom', 'Being alone', 'Criticism', 'Routine', 'Abstract discussions', 'Long-term planning', 'Conflict', 'Feeling left out'],
      hobbies: ['Performing arts', 'Dancing', 'Party planning', 'Fashion', 'Social media', 'Travel', 'Comedy', 'Music festivals'],
      habits: ['Loves being center of attention', 'Plans spontaneous adventures', 'Enjoys entertaining others', 'Lives for the moment'],
      skills: ['Performance', 'Social skills', 'Improvisation', 'Making others happy', 'Hands-on activities'],
      speechPatterns: ['Speaks enthusiastically', 'Uses expressive body language', 'Tells engaging stories', 'Focuses on fun', 'Inclusive language'],
    },
    intense: {
      spectrums: { introvertExtrovert: 98, intuitiveObservant: 90, thinkingFeeling: 90, judgingProspecting: 98, assertiveTurbulent: 60 },
      bigFive: { openness: 60, conscientiousness: 15, extraversion: 98, agreeableness: 80, neuroticism: 55 },
      hexaco: { honestyHumility: 60, emotionality: 60, extraversion: 98, agreeableness: 80, conscientiousness: 15, opennessToExperience: 60 },
      disc: { dominance: 25, influence: 98, steadiness: 30, conscientiousness: 10 },
      discType: 'I',
      strengthsFinder: ['Woo', 'Positivity', 'Communication', 'Activator', 'Adaptability'],
      enneagram: { type: 7, wing: 8, instinctualVariant: 'sx' },
      likes: ['Maximum fun always', 'Being the life of every party', 'Non-stop entertainment', 'Making everyone laugh', 'Living like there\'s no tomorrow', 'Sensory overload', 'Creating unforgettable moments', 'Being adored'],
      dislikes: ['Being bored for even a moment', 'Silence', 'Being alone', 'Having to calm down', 'Responsibility', 'Missing the fun', 'Sadness', 'FOMO'],
      hobbies: ['Karaoke', 'Club dancing', 'Festival going', 'Stand-up comedy', 'Event hosting', 'Social media stardom', 'Beach parties', 'Talent shows'],
      habits: ['Always the loudest in the room', 'Cannot sit still', 'Turns everything into a performance', 'Leaves a trail of laughter everywhere'],
      skills: ['Pure entertainment', 'Social magnetism', 'Creating joy', 'Living in the moment', 'Infectious energy'],
      speechPatterns: ['Everything is exciting!', 'Exaggerated expressions', 'Storytelling as performance', 'Physical comedy', 'Never a dull moment in conversation'],
    },
    nuanced: {
      spectrums: { introvertExtrovert: 80, intuitiveObservant: 75, thinkingFeeling: 70, judgingProspecting: 75, assertiveTurbulent: 50 },
      bigFive: { openness: 60, conscientiousness: 40, extraversion: 80, agreeableness: 70, neuroticism: 45 },
      hexaco: { honestyHumility: 60, emotionality: 50, extraversion: 80, agreeableness: 70, conscientiousness: 40, opennessToExperience: 60 },
      disc: { dominance: 25, influence: 75, steadiness: 45, conscientiousness: 30 },
      discType: 'IS',
      strengthsFinder: ['Positivity', 'Empathy', 'Communication', 'Adaptability', 'Developer'],
      enneagram: { type: 7, wing: 6, instinctualVariant: 'so/sp' },
      likes: ['Small group adventures', 'Making people smile in everyday moments', 'Creative hobbies', 'Cooking for friends', 'Dancing in the living room', 'Outdoor activities', 'Cozy movie nights', 'Surprising loved ones'],
      dislikes: ['Forced socializing', 'Being the center of negative attention', 'Missing genuine moments', 'Being reduced to just "fun"', 'Superficial relationships'],
      hobbies: ['Home cooking', 'Gardening', 'Craft cocktails', 'Photography', 'Pet care', 'Dance classes', 'Board game nights', 'Interior decorating'],
      habits: ['Brings warmth to small groups', 'Notices when someone needs cheering up', 'Creates fun in everyday moments', 'Values quality time over quantity'],
      skills: ['Everyday joy creation', 'Reading the room emotionally', 'Practical creativity', 'Genuine connection', 'Spontaneous kindness'],
      speechPatterns: ['Warm and genuine enthusiasm', 'Asks how people are really doing', 'Shares funny observations', 'Down-to-earth humor', 'Makes everyone feel included'],
    },
  },
}

// ─── All Enneagram Wing Options ───────────────────────────────────────────────
// Traditional Enneagram only allows adjacent wings, but this expanded list
// allows any wing combination for more creative personality expression
export const ENNEAGRAM_WING_OPTIONS: Record<number, number[]> = {
  1: [2, 9, 3, 4, 5, 6, 7, 8],
  2: [1, 3, 4, 5, 6, 7, 8, 9],
  3: [2, 4, 1, 5, 6, 7, 8, 9],
  4: [3, 5, 2, 6, 7, 8, 9, 1],
  5: [4, 6, 3, 7, 8, 9, 1, 2],
  6: [5, 7, 4, 8, 9, 1, 2, 3],
  7: [6, 8, 5, 9, 1, 2, 3, 4],
  8: [7, 9, 6, 1, 2, 3, 4, 5],
  9: [8, 1, 7, 2, 3, 4, 5, 6],
}

// Labels for wing rarity/fit
export const WING_RARITY: Record<string, 'common' | 'uncommon' | 'rare'> = {
  // Type 1: 1w2 and 1w9 are common/adjacent
  '1-2': 'common', '1-9': 'common',
  '1-3': 'uncommon', '1-4': 'uncommon',
  '1-5': 'rare', '1-6': 'rare', '1-7': 'rare', '1-8': 'rare',
  // Type 2: 2w1 and 2w3 are common/adjacent
  '2-1': 'common', '2-3': 'common',
  '2-4': 'uncommon', '2-9': 'uncommon',
  '2-5': 'rare', '2-6': 'rare', '2-7': 'rare', '2-8': 'rare',
  // Type 3: 3w2 and 3w4 are common/adjacent
  '3-2': 'common', '3-4': 'common',
  '3-1': 'uncommon', '3-5': 'uncommon',
  '3-6': 'rare', '3-7': 'rare', '3-8': 'rare', '3-9': 'rare',
  // Type 4: 4w3 and 4w5 are common/adjacent
  '4-3': 'common', '4-5': 'common',
  '4-2': 'uncommon', '4-6': 'uncommon',
  '4-1': 'rare', '4-7': 'rare', '4-8': 'rare', '4-9': 'rare',
  // Type 5: 5w4 and 5w6 are common/adjacent
  '5-4': 'common', '5-6': 'common',
  '5-3': 'uncommon', '5-7': 'uncommon',
  '5-1': 'rare', '5-2': 'rare', '5-8': 'rare', '5-9': 'rare',
  // Type 6: 6w5 and 6w7 are common/adjacent
  '6-5': 'common', '6-7': 'common',
  '6-4': 'uncommon', '6-8': 'uncommon',
  '6-1': 'rare', '6-2': 'rare', '6-3': 'rare', '6-9': 'rare',
  // Type 7: 7w6 and 7w8 are common/adjacent
  '7-6': 'common', '7-8': 'common',
  '7-5': 'uncommon', '7-9': 'uncommon',
  '7-1': 'rare', '7-2': 'rare', '7-3': 'rare', '7-4': 'rare',
  // Type 8: 8w7 and 8w9 are common/adjacent
  '8-7': 'common', '8-9': 'common',
  '8-6': 'uncommon', '8-1': 'uncommon',
  '8-2': 'rare', '8-3': 'rare', '8-4': 'rare', '8-5': 'rare',
  // Type 9: 9w8 and 9w1 are common/adjacent
  '9-8': 'common', '9-1': 'common',
  '9-7': 'uncommon', '9-2': 'uncommon',
  '9-3': 'rare', '9-4': 'rare', '9-5': 'rare', '9-6': 'rare',
}

export function getWingRarity(mainType: number, wing: number): 'common' | 'uncommon' | 'rare' {
  return WING_RARITY[`${mainType}-${wing}`] || 'rare'
}
